feat: add multiple Jenkinsfiles for different testing scenarios and enhance test reporting

diff --git a/Jenkinsfile.simple b/Jenkinsfile.simple
--- a/Jenkinsfile.simple
+++ b/Jenkinsfile.simple
@@ -1,31 +1,31 @@
 pipeline {
-	agent any
+    agent any
 
     environment {
-		PYTHONUNBUFFERED = '1'
-        GEMINI_API_KEY = credentials('GEMINI_API_KEY') // Se debe crear como credential en Jenkins
+        PYTHONUNBUFFERED = '1'
+        GEMINI_API_KEY = credentials('GEMINI_API_KEY')
     }
 
     stages {
-		stage('Clonar repo') {
-			steps {
-				git 'https://github.com/ChristopherPalloArias/JenkinsExample.git'
+        stage('Clonar repo') {
+            steps {
+                git 'https://github.com/ChristopherPalloArias/JenkinsExample.git'
             }
         }
 
         stage('Crear entorno y dependencias') {
-			steps {
-				sh '''
-                python3 -m venv venv
-                ./venv/bin/pip install --upgrade pip
-                ./venv/bin/pip install -r requirements.txt
+            steps {
+                sh '''
+                    python3 -m venv venv
+                    ./venv/bin/pip install --upgrade pip
+                    ./venv/bin/pip install -r requirements.txt
                 '''
             }
         }
 
         stage('Levantar API FastAPI') {
-			steps {
-				sh '''
+            steps {
+                sh '''
                     cd backend
                     nohup ../venv/bin/uvicorn main:app --host 127.0.0.1 --port 8000 &
                     sleep 5
@@ -36,29 +36,29 @@ pipeline {
                     done
                     echo "❌ Timeout esperando a la API."
                     exit 1
-                    '''
+                '''
             }
         }
 
         stage('Ejecutar pruebas con Pytest') {
-			steps {
-				sh './venv/bin/pytest tests/test_api.py --junitxml=report.xml || true'
+            steps {
+                sh './venv/bin/pytest tests/test_api.py --junitxml=report.xml || true'
             }
         }
 
         stage('Publicar resultados de pruebas') {
-			steps {
-				junit 'report.xml'
+            steps {
+                junit 'report.xml'
             }
         }
     }
 
     post {
-		success {
-			echo '✅ La API funciona correctamente y pasó el control de calidad.'
+        success {
+            echo '✅ La API funciona correctamente y pasó el control de calidad.'
         }
         failure {
-			echo '❌ La API no pasó el control de calidad. Revisa los errores.'
+            echo '❌ La API no pasó el control de calidad. Revisa los errores.'
         }
     }
 }
